global:
  scrape_interval: 15s

  scrape_timeout: 10s

scrape_configs:
  - job_name: "scrapping_app"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - ml_app:1702
